//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminTabani_01_05_24
{
    using System;
    using System.Collections.Generic;

    public partial class KullaniciMesajlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KullaniciMesajlar()
        {
            this.KullaniciMesajlarSikayet = new HashSet<KullaniciMesajlarSikayet>();
        }

        public int k_mesaj_id { get; set; }
        public string mesaj { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> gonderen_id { get; set; }
        public Nullable<int> alici_id { get; set; }
        //alici_id
        public virtual Kullanicilar Kullanicilar { get; set; }
        //gonderen_id
        public virtual Kullanicilar Kullanicilar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciMesajlarSikayet> KullaniciMesajlarSikayet { get; set; }
    }
}
