//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminTabani_01_05_24
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciGirisler
    {
        public int giris_id { get; set; }
        public Nullable<System.DateTime> girisTarih { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public Nullable<int> girisKod { get; set; }
        public Nullable<bool> GirisBasarisi1 { get; set; }
        public Nullable<bool> GirisBasarisi2 { get; set; }
        public Nullable<System.DateTime> kodgirisTarih { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
