//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminTabani_01_05_24
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siirler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siirler()
        {
            this.SiirSikayetler = new HashSet<SiirSikayetler>();
            this.SiirYorumlar = new HashSet<SiirYorumlar>();
        }
    
        public int siirID { get; set; }
        public string siirBaslik { get; set; }
        public string icerik { get; set; }
        public Nullable<int> yazar { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<bool> onay { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiirSikayetler> SiirSikayetler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiirYorumlar> SiirYorumlar { get; set; }
    }
}
