//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminTabani_01_05_24
{
    using System;
    using System.Collections.Generic;
    
    public partial class TartismaSikayetler
    {
        public int sikayet_id { get; set; }
        public string sebep { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> sikayetci_id { get; set; }
        public Nullable<int> tartisma_id { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Tartismalar Tartismalar { get; set; }
    }
}
