//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminTabani_01_05_24
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tartismalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tartismalar()
        {
            this.TartismaYorumlar = new HashSet<TartismaYorumlar>();
        }
    
        public int TartismaID { get; set; }
        public string Baslik { get; set; }
        public string icerik { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<bool> onay { get; set; }
        public Nullable<bool> aktiflik { get; set; }
        public Nullable<int> kullanici_id { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TartismaYorumlar> TartismaYorumlar { get; set; }
    }
}
