//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminTabani_01_05_24
{
    using System;
    using System.Collections.Generic;
    
    public partial class YaziYorumlar
    {
        public int YaziYorumID { get; set; }
        public string icerik { get; set; }
        public Nullable<int> yorumcuID { get; set; }
        public Nullable<int> yaziID { get; set; }
        public Nullable<bool> onay { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Yazilar Yazilar { get; set; }
    }
}
